Models/ErrorViewModel.cs
using System;

namespace Roles.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserRole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Roles.Models
{
    public class UserRole
    {
        public string Name { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Roles.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Roles.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Roles.Controllers
{
    [Authorize(Roles="Manager")]
    public class ManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/PolicyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Roles.Controllers
{
    public class PolicyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Policy ="UserAccess")]
        public IActionResult UserPage()
        {
            return View();
        }
        [Authorize(Policy = "ManagerAccess")]
        public IActionResult ManagerPage()
        {
            return View();
        }
        [Authorize(Policy ="AdminAccess")]
        public IActionResult AdminPage()
        {
            return View();
        }
    }
}

Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Roles.Data;
using Roles.Models;
using Roles.ViewModel;
using System.Linq;
using System.Threading.Tasks;

namespace Roles.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;              

        public RolesController(UserManager<IdentityUser> userManager, ApplicationDbContext context, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _context = context;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _context.Roles.ToList();
            var users = _context.Users.ToList();
            var userRoles = _context.UserRoles.ToList();

            var convertedUsers = users.Select(x => new UsersVm
            {
                Email = x.Email,
                Roles = roles
                    .Where(y => userRoles.Any(z => z.UserId == x.Id && z.RoleId == y.Id))
                    .Select(y => new UserRole
                    {
                        Name = y.NormalizedName
                    })
            });

            return View(new DisplayVm
            {
                Roles = roles.Select(x => x.NormalizedName),
                Users = convertedUsers
            });
        }
        // Create user
        public async Task<IActionResult> CreateUser(string email)
        {
            var user = new IdentityUser
            {
                UserName = email,
                Email = email
            };

            await _userManager.CreateAsync(user, "Roskilde001!@");

            return RedirectToAction("Index");
        }
        // Create Role
        public async Task<IActionResult> CreateRole(RoleVm vm)
        {
            await _roleManager.CreateAsync(new IdentityRole { Name = vm.Name });

            return RedirectToAction("Index");
        }

        // Update User Role
        public async Task<IActionResult> UpdateUserRole(UpdateUserRoleVm vm)
        {
            if (vm != null)
            {
                var user = await _userManager.FindByEmailAsync(vm.UserEmail);

                if (vm.Delete)
                    await _userManager.RemoveFromRoleAsync(user, vm.Role);
                else
                    await _userManager.AddToRoleAsync(user, vm.Role);
            }          

            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Manager/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Policy/AdminPage.cshtml
<h1>Admin Page</h1>

Views/Policy/Index.cshtml
<h1>Index Page</h1>

<a asp-controller="Policy" asp-action="UserPage">User Page</a>
<br />
<a asp-controller="Policy" asp-action="ManagerPage">Manager Page</a>
<br />
<a asp-controller="Policy" asp-action="AdminPage">Admin Page</a>

Views/Policy/ManagePage.cshtml
<h1>Manager Page</h1>

Views/Policy/UserPage.cshtml
<h1>User Page</h1>

Views/Roles/Index.cshtml
@model DisplayVm

@{ }

<div>
    <h2>Create User</h2>
    <div>
        <form asp-controller="Roles" asp-action="CreateUser" method="post">
            <label>User Email</label>
            <input name="email" value="" />
            <input type="submit" value="Create User" />
        </form>
    </div>
</div>
<div>
    <div>
        <h2>Role List</h2>
        <ul>
            @foreach (var role in Model.Roles)
            {
                <li>
                    @role
                </li>       
            }
        </ul>
    </div>
    <partial name="_CreateRolePartial" model=" new RoleVm()" >
</div>
<div>
    <partial name="_AddUserToRolePartial" model="new UpdateUserRoleVm() { Users =@Model.Users, Roles = @Model.Roles}" >
</div>

Views/Roles/_AddUserToRolePartial.cshtml
@model UpdateUserRoleVm

@{ 
// razor code here if yo need that
}

<div>
    <form asp-controller="Roles" asp-action="UpdateUserRole" method="post">
        <h2>Add User to Role</h2>
        <div>
            @foreach (var user in @Model.Users)
            {
            <div>
                <input type="radio" asp-for="@Model.UserEmail" value="@user.Email" />
                @user.Email
            </div>
                <div>                    
                        @foreach (var role in user.Roles)
                        {
                           <div>
                              @role.Name
                           </div>
                        }                   
                </div> 
            }
        </div>
        <h4>Roles to add</h4>
        <div>
            @foreach (var role in @Model.Roles)
              {
                <div>
                    <input type="radio" asp-for="Role" value="@role" />
                    @role
                </div>          
              }
        </div>
        <input type="submit" value="Add Role" />
        <input type="hidden" asp-for="Delete" value="false" id="delete" />
        <input type="submit" value="Delete Role" onclick="document.getElementById('delete').value = 'true'" />
    </form>
</div>

Views/Roles/_CreateRolePartial.cshtml
@model RoleVm

@{ }

<div>
    <form asp-controller="Roles" asp-action="CreateRole" method="post">
        <label>Create new Role</label>
        <input asp-for="@Model.Name" />
        <input type="submit" value="Create" />
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Roles</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Roles</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Role Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Policy" asp-action="Index">Policy Test</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Roles - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>